### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by TimenoLong** [MarcWangzhiru/SpeclatentGS#4]
My environment is fine, both PyTorch and CUDA are installed correctly, and tiny-cuda-nn is also successfully installed. I have tried both version 1.6 and 1.7. However, when running your code, CUDA cannot be detected in the tiny-cuda-nn code, while everything else works fine. Do you have any good solutions?

![图片1](https://github.com/user-attachments/assets/cbe00267-80a5-45b8-a249-c6a91adc0d5f)
![图片2](https://github.com/user-attachments/assets/cc6f9fbb-01fd-4821-9852-81185c614beb)

(base) root@autodl-container-49d843b6cc-164b0342:~/tiny/speclatentGS# python train.py -s /root/autodl-tmp/shiny_dataset/cd --eval
version:  1.11.0+cu113
CUDA version: 11.3
False
0
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from gaussian_renderer import render, network_gui
  File "/root/tiny/speclatentGS/gaussian_renderer/__init__.py", line 17, in <module>
    from scene.gaussian_model import GaussianModel
  File "/root/tiny/speclatentGS/scene/__init__.py", line 17, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/root/tiny/speclatentGS/scene/dataset_readers.py", line 24, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/root/tiny/speclatentGS/scene/gaussian_model.py", line 23, in <module>
    import tinycudann as tcnn
  File "/root/miniconda3/lib/python3.8/site-packages/tinycudann-1.6-py3.8-linux-x86_64.egg/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/root/miniconda3/lib/python3.8/site-packages/tinycudann-1.6-py3.8-linux-x86_64.egg/tinycudann/modules.py", line 18, in <module>
    print(torch.cuda.current_device()) 
  File "/root/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 481, in current_device
    _lazy_init()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by 791515391** [comment]
我遇到同样的问题
RuntimeError: No CUDA GPUs are available
